package by.epam.task03.entities;


public enum MenuTagName {
    MENU, TYPEOFMENU, ID, IMG, TITLE, DESCRIPTION, PORTION, WEIGHT, RATION_1, RATION_2, RATION_3, RATION_4,
    CURRENCY, PRICE, QUANTITY
}
